### PR TITLE
Feat: FE - disable login button on login, fix regex for dates

### PR DESCRIPTION
**Pull request by artikandri**
# Description

This PR handles the requests to disable the login button after clicking on it for 5 seconds. Additionally, I also fixed the regex to handle dates that started with `dzień` in the markdown component.

**Type of change**

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactor (change restructuring the codebase without changing functionality)
- [x] Improvement (change adding some improvement to an existing functionality)

**How Has This Been Tested**

Screenshot from 2023-10-30 19-08-23
Screenshot from 2023-10-30 19-18-10

**Checklist**

- [ ] I added relevant documentation
- [x] I followed the style guidelines of this project
- [x] I did a self-review of my code
- [ ] I made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I filled out [the contributor form](https://tally.so/r/n9XrxK) (see text above)
- [ ] I have added relevant notes to the `CHANGELOG.md` file (See https://keepachangelog.com/)

**Modified files**

- `frontend/components/base/render-markdown/RenderMarkdown.base.component.vue`: Updated the rule, now it will exclude numbers preceeded by `dzień` and not ended with ` `.
- `frontend/pages/login.vue` : disabled the button

**Screenshots: **
Screenshot from 2023-10-30 16-46-39
Screenshot from 2023-10-30 18-00-59

### CODE REVIEW

**Comment by dvsrepo** [comment]
Hi!

This is Dani, co-founder of Argilla, it's very cool to see you are using Argilla for the Clarin-PL projects. We'd love to chat and see if some of you modifications could be contributed/added to the core project.

cc @davidberenstein1957

**Review by Netherwulf — APPROVED** [review]
Important changes focused on improving the user experience.

**Comment by dvsrepo** [comment]
> Important changes focused on improving the user experience.

Thanks. If they improve the user experience don't you think they'll be very useful for other community users of this open source project?

**Comment by artikandri** [comment]
@Netherwulf  Thank you for the feedback :)  I will merge it now

@dvsrepo  Hello, thank you for reaching out to us.  We are excited with the possibility of contributing to the project, however right now we need to focus on our project, so it can't be done right away. Is that fine?

**Comment by dvsrepo** [comment]
> @Netherwulf Thank you for the feedback :) I will merge it now
> 
> @dvsrepo Hello, thank you for reaching out to us. We are excited with the possibility of contributing to the project, however right now we need to focus on our project, so it can't be done right away. Is that fine?

that's perfect! Ping us whenever you think is useful to chat, we'd be happy to help too if you have any issues.

**Pull request merged**
